### ISSUE TITLE
Homework 2 for Sheng Guo

### ISSUE THREAD

**Issue by anyezijue49** [anyezijue49/stat679work#3]
Hi Professor @cecileane

Here is my homework: b0146f00630bf65a8683198bba66745309d76054
Please make sure that your current directory include `waterTemperature.csv` and `energy.csv` when you run `HW2.py`.
You should enter the filenames of two csv files without a `.csv` extension.
If you have other problems, please contact with me.
Thank you

Best,
Sheng Guo

**Comment by cecileane** [comment]
Hi Sheng,

Nice job! More details below.

## overall presentation

You are currently tracking 2 weird files with git: one named `excuseme` whose content is simply `are you kidding me?`, another one named `excuseme.csv`, and a file `Untitled.ipynb` containing a single empty cell. If you publish/share any project with git later (or if you work for a company that uses git internally), it will be useful to control exactly what you commit. For example, doing `git add .` is not a good thing to do, to track new files.

It would have been best to organize your files with separate directories for your script and for your data / result files.

In your github issue, you say that we should "make sure that your current directory include `waterTemperature.csv` and `energy.csv` when you run `HW2.py`". But these input files could really be anywhere, and the script could really be anywhere. I placed your script in a folder `script/`, copied the data files in a folder `data`, then I ran your script like this and it worked, with the path to the script and to each input file:

```shell
script/HW2.py -t data/waterTemperature -e data/energy
```

It would have been best to add another option to let the user choose the name of the output file. You used the argparse library, so it would have been an easy thing to add.

You should have written a readme file to explain how to use your script (with the line above for instance), and with an explanation of any assumptions made by your script. Even in your github issue, you don't say if the temperature file should come first or if the energy file should come first. The problem had instructions on this, but the user won't see these instructions!

## running your script

The good thing is that you used the argparse library, so the script itself gives some help about how to use it. I got an error when trying to run your file with the correct argument usage, like this:

```shell
$ python HW2.py -temperature waterTemperature.csv -energy energy.csv
Traceback (most recent call last):
  File "HW2.py", line 67, in <module>
    main()
  File "HW2.py", line 23, in main
    with open(filename1,"r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'waterTemperature.csv.csv'
```

Your script changes the name of the file, adding a `.csv` at the end (explained in the help for the script). This is not a good choice though, because we typically never type the full name of data files: we type the beginning and then use TAB completion to let the shell finish typing the rest of the file name. That will include the extension. Your choice also forces the file name to end with `.csv`. Sometimes, files are written in csv format even if their names doesn't end with `.csv`. Your script could not use such files, unfortunately.

Unfortunately, your output has an energy value on each line, as if energy data were collected hourly instead of daily:

```shell
$ cat output.csv
"Plot Title: 10679014 jackson July29"
"#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",Energy Produced (Wh)

1,07/29/16 10:26:34 AM,72.86,9.468

2,07/29/16 11:26:34 AM,73.92,9.468

3,07/29/16 12:26:34 PM,73.98,9.468

4,07/29/16 01:26:34 PM,74.86,9.468

5,07/29/16 02:26:34 PM,75.34,9.468

...
13,07/29/16 10:26:34 PM,73.27,9.468

14,07/29/16 11:26:34 PM,73.45,9.468

15,07/30/16 12:26:34 AM,72.30,12.062

16,07/30/16 01:26:34 AM,72.70,12.062

...
```

The homework instructions provided an algorithm to place each energy value once.

Also your code didn't get rid of the extra `\r` characters inherited by Windows-style line endings.


## about your code

Nice use of `try/except` blocks!

It would have been best to break your big `main` function into several functions.

You define your important data structures as dictionaries (lines 28-31):

```python
temperature={}
t_date={}
energy={}
e_date={}
```

but you actually use them as lists, because your keys are integers, like on lines 41-43:

```python
e_date[k]=[int(month),int(date)]
energy[k]=float(string[1])/1000
k += 1
```

On line 50, you store the temperature data in `string=line.split(",")`. This is not a well-chosen variable name, because it does not say that it's about temperature, and it suggests that the object is a string, when it's in fact a list.

Also on line 62 you assume that all months have 31 days (like July). Even if we sometimes need to make suboptimal assumptions, it is extra-important to talk about these assumptions as comments in the script, and in a readme file. Such comments can remind ourselves to remove these assumptions later, after more serious bugs are fixed.

You can go ahead and close this issue now.
